name: Android CI & Startup Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Run unit tests
        run: ./gradlew :WebradioApp:app:testDebugUnitTest

      - name: Run Android Instrumented Tests (includes app launch)
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86
          profile: Nexus 6
          cold-boot: false
          disable-animations: true
          emulator-options: -no-window -no-audio -memory 4096
          emulator-timeout: 600 # Attend jusqu'à 10 minutes pour le démarrage
          wait-for-emulator: true
          script: ./gradlew :WebradioApp:app:connectedDebugAndroidTest
