name: Manual Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Checkout - Root
      run: ls -la

    - name: Show Current Directory # New
      run: pwd

    - name: Stat WebradioApp Directory # New
      run: stat WebradioApp/

    - name: Attempt to cd into WebradioApp and list contents # Modified/Replaces several ls steps
      run: |
        cd WebradioApp || exit 1
        echo "Successfully changed to WebradioApp directory. Current path:"
        pwd
        echo "Contents of WebradioApp:"
        ls -la
        # Attempt to cd back to GITHUB_WORKSPACE to not affect subsequent steps if they rely on it.
        # However, if cd WebradioApp fails, the script exits due to 'exit 1', so cd $GITHUB_WORKSPACE might not run.
        # A safer approach might be to run these in a subshell if we were concerned about pwd for next steps,
        # but for now, let's see the output. If this step succeeds, subsequent steps might operate
        # from within WebradioApp if not explicitly changed back.
        # For now, the primary goal is to see if 'cd WebradioApp' works.
        # Let's add a cd back for safety for subsequent steps, assuming this one passes.
        cd $GITHUB_WORKSPACE

    - name: Delete local.properties files # New step
      run: |
        find . -name local.properties -print -delete
        echo "Ensured no local.properties files exist."

    - name: Set up JDK 17
      id: setup_jdk # Add an id to reference the output
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Export JAVA_HOME # New step
      run: echo "JAVA_HOME=${{ steps.setup_jdk.outputs.jdk-path }}" >> $GITHUB_ENV

    - name: Verify Java installation # New step
      run: |
        java -version
        echo "JAVA_HOME is: $JAVA_HOME"

    # - name: List contents of font directory # Temporarily commented out
    #  run: ls -la WebradioApp/app/src/main/res/font/

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle # Modified step
      run: ./gradlew clean build --stacktrace --info
