name: Build Jules CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show GITHUB_WORKSPACE structure
      run: |
        echo "GITHUB_WORKSPACE is: ${{ github.workspace }}"
        ls -R ${{ github.workspace }}
      shell: bash

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Android SDK 33 and Build-Tools
      run: |
        yes | sdkmanager --licenses
        yes | sdkmanager "platforms;android-33" "build-tools;33.0.2"

    - name: Delete local.properties files
      run: |
        find . -name local.properties -print -delete
        echo "Ensured no local.properties files exist."
      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: true

    - name: Attempt to regenerate Gradle Wrapper
      run: |
        echo "Attempting to regenerate gradle-wrapper.jar using 'gradle wrapper' command..."
        gradle wrapper --gradle-version 8.5 --stacktrace
        echo "Listing contents of gradle/wrapper/ after attempt:"
        ls -l gradle/wrapper/
      shell: bash

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Show current directory before build
      run: pwd
      shell: bash

    - name: Build with Gradle
      run: ./gradlew :WebradioApp:app:clean :WebradioApp:app:assembleDebug --stacktrace --info

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: WebradioApp/app/build/outputs/apk/debug/app-debug.apk