name: Manual Android Build2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Checkout - Root
      run: ls -la
    - name: Verify Checkout - WebradioApp # Restored
      run: ls -la WebradioApp/
    - name: Verify Checkout - WebradioApp app # Restored
      run: ls -la WebradioApp/app/
    - name: Verify Checkout - WebradioApp app src # Restored
      run: ls -la WebradioApp/app/src/
    - name: Verify Checkout - WebradioApp app src main # Restored
      run: ls -la WebradioApp/app/src/main/
    - name: Verify Checkout - WebradioApp app src main res # Restored
      run: ls -la WebradioApp/app/src/main/res/
    - name: Delete local.properties files # New step
      run: |
        find . -name local.properties -print -delete
        echo "Ensured no local.properties files exist."

    - name: Set up JDK 17
      id: setup_jdk # Add an id to reference the output
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Export JAVA_HOME # New step
      run: echo "JAVA_HOME=${{ steps.setup_jdk.outputs.jdk-path }}" >> $GITHUB_ENV

    - name: Verify Java installation # New step
      run: |
        java -version
        echo "JAVA_HOME is: $JAVA_HOME"

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle # Modified step
      run: |
        ls -la gradle/wrapper/
        ./gradlew :WebradioApp:app:clean :WebradioApp:app:build --stacktrace --info