name: Manual Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      id: setup_jdk # Add an id to reference the output
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Export JAVA_HOME # New step
      run: echo "JAVA_HOME=${{ steps.setup_jdk.outputs.jdk-path }}" >> $GITHUB_ENV

    - name: Verify Java installation # New step
      run: |
        java -version
        echo "JAVA_HOME is: $JAVA_HOME"

    - name: List contents of font directory # New step
      run: ls -la WebradioApp/app/src/main/res/font/

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle # Modified step
      run: ./gradlew clean build --stacktrace --info
