name: Manual Android Build

on:
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Debug project structure
        run: |
          echo "Listing root directory:"
          ls -la ${{ github.workspace }}
          echo "Listing WebradioApp directory:"
          ls -la ${{ github.workspace }}/WebradioApp || echo "WebradioApp not found"

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: ${{ github.workspace }}/WebradioApp

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: ${{ github.workspace }}/WebradioApp

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: webradio-debug-apk
          path: ${{ github.workspace }}/WebradioApp/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error