name: Android CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Download and install Android SDK Command Line Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d .
        mv cmdline-tools latest

        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --update
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
          "platforms;android-34" \
          "build-tools;34.0.0" \
          "platform-tools"

    - name: Ensure no local.properties is present
      run: find . -name local.properties -print -delete

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Setup Gradle (without cache)
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: true

    - name: Network Connectivity Diagnostics
      run: |
        echo "--- Testing connectivity to Gradle Plugin Portal (Base URL) ---"
        curl -I --fail-with-body --connect-timeout 10 https://plugins.gradle.org/m2/ || echo "Failed to connect to Gradle Plugin Portal base URL"
        echo "--- Testing connectivity to Maven Central (Base URL) ---"
        curl -I --fail-with-body --connect-timeout 10 https://repo.maven.apache.org/maven2/ || echo "Failed to connect to Maven Central base URL"

        echo "--- Testing connectivity to AGP POM ---"
        curl -I --fail-with-body --connect-timeout 10 https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.2.2/gradle-8.2.2.pom || echo "Failed to connect to AGP POM"
        echo "--- Testing connectivity to Kotlin Gradle Plugin POM ---"
        curl -I --fail-with-body --connect-timeout 10 https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.9.0/kotlin-gradle-plugin-1.9.0.pom || echo "Failed to connect to Kotlin Gradle Plugin POM"
        echo "--- Testing connectivity to SafeArgs Plugin POM ---"
        curl -I --fail-with-body --connect-timeout 10 https://dl.google.com/dl/android/maven2/androidx/navigation/navigation-safe-args-gradle-plugin/2.5.3/navigation-safe-args-gradle-plugin-2.5.3.pom || echo "Failed to connect to SafeArgs Plugin POM"
        echo "--- Network diagnostics complete ---"
      continue-on-error: true # Allow the workflow to continue even if curl commands fail, so build can be attempted

    - name: Build APK (debug)
      run: ./gradlew :WebradioApp:app:assembleDebug --stacktrace --info --no-daemon > build_output.log 2>&1

    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-log.txt # Artifact name will be build-log.txt
        path: build_output.log
        retention-days: 7

    - name: Capture Kotlin compile logs if build fails
      if: failure()
      run: |
        echo "::group::Kotlin Compiler Logs"
        find . -type f -name "*.log" -exec cat {} \;
        echo "::endgroup::"

    # - name: Run Unit Tests (optional)
    #   run: ./gradlew :WebradioApp:app:testDebugUnitTest --no-daemon --info

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: WebradioApp/app/build/outputs/apk/debug/app-debug.apk
