name: Build Jules CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Show GITHUB_WORKSPACE structure
      run: |
        echo "GITHUB_WORKSPACE is: ${{ github.workspace }}"
        ls -R ${{ github.workspace }}
      shell: bash

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Android SDK Command Line Tools and SDK 33
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/Android/cmdline-tools
        unzip cmdline-tools.zip -d $HOME/Android/cmdline-tools
        mkdir -p $HOME/Android/sdk/cmdline-tools/latest
        mv $HOME/Android/cmdline-tools/cmdline-tools/* $HOME/Android/sdk/cmdline-tools/latest/

        # Set environment variables correctly (resolve conflict)
        echo "ANDROID_SDK_ROOT=$HOME/Android/sdk" >> $GITHUB_ENV
        echo "ANDROID_HOME=" >> $GITHUB_ENV  # Désactive la variable conflictuelle
        echo "$HOME/Android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

        # Install SDK components
        yes | sdkmanager --licenses || true
        sdkmanager --update
        sdkmanager "platforms;android-33" "build-tools;33.0.2"
      shell: bash

    - name: Delete local.properties files
      run: |
        find . -name local.properties -print -delete
        echo "Ensured no local.properties files exist."
      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: true

    - name: Show current directory before build
      run: pwd
      shell: bash

    - name: Debug environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_HOME"
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"

    - name: Build with Gradle
      run: ./gradlew :WebradioApp:app:clean :WebradioApp:app:assembleDebug --stacktrace --info

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: WebradioApp/app/build/outputs/apk/debug/app-debug.apk
