name: Build Jules CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Android SDK Command Line Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
      shell: bash

    - name: Accept SDK Licenses and Install SDK Packages
      run: |
        sdkmanager --sdk_root=$ANDROID_HOME --licenses || true
        sdkmanager --sdk_root=$ANDROID_HOME --update
        sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-33" "build-tools;33.0.2" "platform-tools"
      shell: bash

    - name: Clean local.properties
      run: |
        find . -name local.properties -print -delete
      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: true

    - name: Build with Gradle
      run: ./gradlew :WebradioApp:app:clean :WebradioApp:app:assembleDebug --stacktrace --info

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: WebradioApp/app/build/outputs/apk/debug/app-debug.apk
